"""Add token usage tracking table

Revision ID: 4d99beca71c2
Revises: 2e5f176bd178
Create Date: 2025-06-11 15:30:07.437414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d99beca71c2"
down_revision: Union[str, None] = "2e5f176bd178"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("input_cost", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("output_cost", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("total_cost", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["my_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "model_name", "year", "month", name="unique_agent_model_month"
        ),
    )
    op.create_index(
        "ix_token_usage_agent_id", "token_usage", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_token_usage_agent_year_month",
        "token_usage",
        ["agent_id", "year", "month"],
        unique=False,
    )
    op.create_index(
        "ix_token_usage_model_name", "token_usage", ["model_name"], unique=False
    )
    op.create_index(
        "ix_token_usage_year_month", "token_usage", ["year", "month"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_token_usage_year_month", table_name="token_usage")
    op.drop_index("ix_token_usage_model_name", table_name="token_usage")
    op.drop_index("ix_token_usage_agent_year_month", table_name="token_usage")
    op.drop_index("ix_token_usage_agent_id", table_name="token_usage")
    op.drop_table("token_usage")
    # ### end Alembic commands ###
