"""Initial migration - preserve ADK tables

Revision ID: 607e2fda5453
Revises:
Create Date: 2025-06-05 17:53:34.743493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '607e2fda5453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration preserves ADK core tables which are essential for system function
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Since upgrade() does nothing, downgrade() should also do nothing
    pass
    # ### end Alembic commands ###
