"""init

Revision ID: b96dd8b9fff2
Revises: 
Create Date: 2025-05-21 11:10:43.112669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b96dd8b9fff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_states')
    op.drop_table('agent_configs')
    op.drop_table('events')
    op.drop_table('user_states')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', 'id', name='sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_states',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', name='user_states_pkey')
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('invocation_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('long_running_tool_ids_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grounding_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('partial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('turn_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('interrupted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_name', 'user_id', 'session_id'], ['sessions.app_name', 'sessions.user_id', 'sessions.id'], name='events_app_name_user_id_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'app_name', 'user_id', 'session_id', name='events_pkey')
    )
    op.create_table('agent_configs',
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role_instruction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tools_instruction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('use_function_map', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_name', name='agent_configs_pkey')
    )
    op.create_table('app_states',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', name='app_states_pkey')
    )
    # ### end Alembic commands ###
